import type { NextPage } from 'next'
import Head from 'next/head'

import { Container } from '../src/components/Container'
import { Title } from '../src/components/Title'
import { Diagram } from '../src/components/Diagram'
import { Code } from '../src/Code'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>test-task</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Container>
                <Title />
                <Diagram />
                <Code />
            </Container>
        </div>
    )
}

export default Home
